#!/usr/bin/env bash
set -euo pipefail

# 1-chip analog/cosim event smoke test.
#
# Test intent:
# - instantiate the minimal LArPix network stack: orchestrator_larpix,
#   fpga_larpix, and one chip_larpix process using the real analog + Verilated
#   digital core backend
# - inject startup configuration writes from the FPGA over the south edge to:
#   enable south TX, enable channel 0, unmask channel 0, and disable trigger
#   veto modes
# - apply one charge pulse to channel 0 through the chip's local stimulus JSON
# - verify that the FPGA receives a valid downstream data packet generated by
#   the chip from that injected charge
#
# Required passing conditions:
# - build/chip_larpix exists and runs with the real analog + Verilated digital core
# - build/fpga_larpix injects all startup configuration writes
# - the single charge stimulus is applied on channel 0 after configuration
# - fpga_larpix receives at least one valid data packet
# - a decoded received packet matches chip_id=1, channel_id=0, downstream=1,
#   trigger_type=0, and passes odd parity

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
build_dir="$repo_root/build"
work_dir="$build_dir/larpix_1chip_event_smoke"
startup_in="$repo_root/larpix_network_sim/config/startup_1chip_event_source.json"
stimulus_json="$repo_root/larpix_network_sim/config/stimulus_1chip_event_source.json"
startup_compiled="$work_dir/startup_1chip_event_source.compiled.json"
log_file="$work_dir/run.log"

mkdir -p "$work_dir"

cmake -S "$repo_root" -B "$build_dir"
cmake --build "$build_dir" --target fpga_larpix orchestrator_larpix chip_larpix_build -j

python3 "$repo_root/larpix_network_sim/scripts/compile_startup_json.py" \
  "$startup_in" \
  "$startup_compiled"

ticks=$(python3 - "$startup_compiled" <<'PYT'
import json
import pathlib
import sys
path = pathlib.Path(sys.argv[1])
raw = json.loads(path.read_text())
frames = raw.get('frames', [])
last_tick = max((int(frame['tick_start']) for frame in frames), default=0)
print(last_tick + 900)
PYT
)

"$build_dir/orchestrator_larpix" \
  -rows 1 \
  -cols 1 \
  -ticks "$ticks" \
  -source_x 0 \
  -source_y 0 \
  -chip_bin "$build_dir/chip_larpix" \
  -fpga_bin "$build_dir/fpga_larpix" \
  -startup_json "$startup_compiled" \
  -stimulus_json "$stimulus_json" \
  > "$log_file" 2>&1

python3 - "$log_file" "$repo_root/larpix_network_sim/scripts/larpix_uart.py" <<'PY2'
import importlib.util
import pathlib
import re
import sys

log_path = pathlib.Path(sys.argv[1])
helper_path = pathlib.Path(sys.argv[2])
text = log_path.read_text()
match = re.findall(r"received packet at seq=\d+: (0x[0-9a-fA-F]+)", text)
if not match:
    print(text)
    raise SystemExit('FAIL: fpga_larpix did not receive any packet')

spec = importlib.util.spec_from_file_location('larpix_uart', helper_path)
mod = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = mod
spec.loader.exec_module(mod)

data_packets = []
for raw in match:
    word = int(raw, 0)
    fields = mod.decode_packet(word)
    if fields.kind == 'data':
        data_packets.append((word, fields))

if not data_packets:
    print(text)
    raise SystemExit('FAIL: fpga_larpix received packets, but none decoded as data packets')

selected_word = None
selected_fields = None
for word, fields in data_packets:
    decoded = fields.decoded
    if (
        fields.odd_parity_ok
        and decoded['chip_id'] == 1
        and decoded['channel_id'] == 0
        and decoded['downstream'] == 1
        and decoded['trigger_type'] == 0
    ):
        selected_word = word
        selected_fields = fields
        break

if selected_fields is None:
    details = []
    for word, fields in data_packets[:10]:
        d = fields.decoded
        details.append(
            f"0x{word:016x}: chip_id={d.get('chip_id')} channel_id={d.get('channel_id')} "
            f"adc={d.get('adc')} downstream={d.get('downstream')} "
            f"trigger_type={d.get('trigger_type')} parity_ok={fields.odd_parity_ok}"
        )
    raise SystemExit(
        'FAIL: no received data packet matched chip_id=1, channel_id=0, downstream=1, trigger_type=0\n'
        + '\n'.join(details)
    )

adc = selected_fields.decoded['adc']
if adc <= 0:
    raise SystemExit(f'FAIL: expected positive ADC code in event packet, got {adc}')

print('PASS: 1-chip LArPix analog/cosim event smoke test')
print(f'reply_packet=0x{selected_word:016x}')
print(
    'chip_id={chip_id} channel_id={channel_id} adc={adc} downstream={downstream} trigger_type={trigger_type}'.format(
        **selected_fields.decoded
    )
)
PY2
