onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:output_event
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:regmap_write_data
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:regmap_address
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:write_fifo_n
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:read_fifo_n
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:ld_tx_data
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:write_regmap
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:read_regmap
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:rx_data
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:pre_event
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:chip_id
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:regmap_read_data
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:rx_data_flag
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:fifo_empty
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:tx_busy
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:load_event
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:clk_ctrl
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:clk
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:reset_n
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:State
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:Next
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:comms_ctrl_inst:read_latency
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:output_event
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:write_fifo_n
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:read_fifo_n
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:tx_data
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:chip_id
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:pre_event
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:fifo_full
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:fifo_half
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:fifo_empty
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:load_event
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:load_config_defaults
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:test_mode
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:timestamp_32b
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:enable_miso_upstream
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:enable_miso_downstream
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:enable_mosi
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:differential_uart
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:clk_rx
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:clk_tx
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:clk_ctrl
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:clk
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:reset_n_clk
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:reset_n_config
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:data_wo_parity
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:fifo_full_delayed
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:fifo_half_delayed
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:rx_data_flag
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:rx_empty_uart
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:uld_rx_data_uart
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:ld_tx_data
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:ld_tx_data_uart
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:rx_enable
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:tx_enable
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:tx_busy
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:tx_busy_any
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:rx_data
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:regmap_write_data
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:regmap_read_data
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:regmap_address
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:write_regmap
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:external_interface_inst:read_regmap
add wave -noupdate -expand :larpix_hydra_tb:larpix_v2_inst0:miso
add wave -noupdate -expand :larpix_hydra_tb:larpix_v2_inst1:mosi
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:output_event
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:regmap_write_data
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:regmap_address
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:write_fifo_n
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:read_fifo_n
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:ld_tx_data
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:write_regmap
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:read_regmap
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:rx_data
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:pre_event
add wave -noupdate -radix decimal :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:chip_id
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:regmap_read_data
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:rx_data_flag
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:fifo_empty
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:tx_busy
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:load_event
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:clk_ctrl
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:clk
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:reset_n
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:State
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:Next
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:comms_ctrl_inst:read_latency
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:write_fifo_n
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst1:digital_core_inst:external_interface_inst:read_regmap
add wave -noupdate -expand :larpix_hydra_tb:miso3
add wave -noupdate -expand :larpix_hydra_tb:miso1
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:mosi
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:channel_event}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:dac_word}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:adc_word}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:fifo_empty}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:triggered_natural}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:csa_reset}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:sample}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:strobe}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:comp}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:hit}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:chip_id}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:channel_id}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:adc_burst}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:adc_hold_delay}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:timestamp_32b}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:reset_length}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:enable_dynamic_reset}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:mark_first_packet}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:read_local_fifo_n}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:external_trigger}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:cross_trigger}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:periodic_trigger}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:periodic_reset}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:enable_min_delta_adc}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:threshold_polarity}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:dynamic_reset_threshold}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:digital_threshold}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:min_delta_adc}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:fifo_full}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:fifo_half}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:fifo_counter}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:enable_fifo_diagnostics}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:channel_mask}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:external_trigger_mask}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:cross_trigger_mask}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:periodic_trigger_mask}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:enable_periodic_trigger_veto}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:enable_hit_veto}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:clk}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:reset_n}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:State}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:Next}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:triggered_external}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:triggered_cross}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:triggered_periodic}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:triggered_channel}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:trigger_type}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:trigger_type_latched}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:sar_mask}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:sample_counter}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:timestamp_latched}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:strobe_en}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:adc_burst_counter}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:reset_counter}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:pre_event}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:delta_adc}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:previous_adc_word}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:first_conversion}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:periodic_reset_triggered}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:csa_reset_triggered}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:csa_reset_held}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:csa_reset_flag}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:last_call}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:final_conversion}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:write_local_fifo_n}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:local_fifo_counter}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:local_fifo_full}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:local_fifo_half}
add wave -noupdate {:larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:strobe_BAR}
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:channel_event_out
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:read_local_fifo_n
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:load_event
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:local_fifo_empty
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:lightpix_mode
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:hit_threshold
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:timeout
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:clk
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:reset_n
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:channel_waiting
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:local_fifo_empty_latched
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:fifo_empty_frozen
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:total_hits
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:event_timer
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:event_accepted
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:event_rejected
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:event_decided
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:State
add wave -noupdate :larpix_hydra_tb:larpix_v2_inst0:digital_core_inst:event_router_inst:Next
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {319013301 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 608
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {317780236 ps} {319831018 ps}
