onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:miso
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:miso_bar
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:dac_word
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:sample
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:strobe
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:csa_gain
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:csa_reset
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:comp
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:hit
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:external_trigger
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:external_trigger_mask
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:channel_mask
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:mosi
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:clk
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:reset_n
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:adc_word
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:clk_ctrl
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:timestamp_32b
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:read_local_fifo_n
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:reset_n_sync
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:clk_core
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:clk_rx
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:clk_tx
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:output_event
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:write_fifo_n
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:read_fifo_n
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:config_bits
add wave -noupdate {:larpix_single_tb:larpix_v2_inst:analog_core_inst:CHANNELS[63]:analog_channel_inst:VOUT_DC_CSA}
add wave -noupdate {:larpix_single_tb:larpix_v2_inst:analog_core_inst:CHANNELS[63]:analog_channel_inst:discriminator_inst:signal_r}
add wave -noupdate {:larpix_single_tb:larpix_v2_inst:analog_core_inst:CHANNELS[63]:analog_channel_inst:discriminator_inst:threshold_r}
add wave -noupdate {:larpix_single_tb:larpix_v2_inst:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:triggered_channel}
add wave -noupdate {:larpix_single_tb:larpix_v2_inst:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:hit}
add wave -noupdate {:larpix_single_tb:larpix_v2_inst:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:State}
add wave -noupdate {:larpix_single_tb:larpix_v2_inst:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:csa_reset}
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:pre_event
add wave -noupdate {:larpix_single_tb:larpix_v2_inst:digital_core_inst:read_local_fifo_n[63]}
add wave -noupdate {:larpix_single_tb:larpix_v2_inst:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:write_local_fifo_n}
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:fifo_top_inst:fifo_ram_inst:clk_read
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:fifo_top_inst:fifo_ram_inst:clk_write
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:adc_burst_length
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:adc_hold_delay
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:reset_length
add wave -noupdate {:larpix_single_tb:larpix_v2_inst:digital_core_inst:sample[63]}
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:clk_core
add wave -noupdate {:larpix_single_tb:larpix_v2_inst:digital_core_inst:strobe[63]}
add wave -noupdate {:larpix_single_tb:larpix_v2_inst:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:strobe_en}
add wave -noupdate {:larpix_single_tb:larpix_v2_inst:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:dac_word}
add wave -noupdate {:larpix_single_tb:larpix_v2_inst:digital_core_inst:CHANNELS[63]:channel_ctrl_inst:adc_word}
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:fifo_top_inst:fifo_ram_inst:clk_read
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:fifo_top_inst:fifo_ram_inst:clk_write
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:fifo_top_inst:fifo_ram_inst:ICGP_W:EN_dly
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:fifo_top_inst:fifo_ram_inst:ICGP_W:CLK
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:fifo_top_inst:fifo_ram_inst:ICGP_W:ENCLK
add wave -noupdate :larpix_single_tb:larpix_v2_inst:digital_core_inst:clk_manager_inst:clk_counter
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 5} {11540081 ps} 0} {{Cursor 6} {201551622 ps} 0} {{Cursor 3} {203650000 ps} 0} {{Cursor 4} {81302521 ps} 0} {{Cursor 5} {203250000 ps} 0} {{Cursor 6} {298884988 ps} 0}
quietly wave cursor active 6
configure wave -namecolwidth 631
configure wave -valuecolwidth 84
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {315 us}
