///////////////////////////////////////////////////////////////////
// File Name: gate_posedge_clk.sv
// Engineer:  Dario Gnani (dgnani@lbl.gov)
// Description: Clock gating logic for posedge-sensitive seq logic.
//              Basic description of integrated clock gating (ICG) cell.
//
// NOTE: pin names must be EN, TE, CLK, ENCLK (!)
///////////////////////////////////////////////////////////////////
`timescale 1ns / 10ps
module gate_posedge_clk
    (output logic ENCLK,           // gated posedge clock
    input logic EN,               // clock-gating: enable clock (active high)
    input logic CLK);             // posedge clock

`ifdef VERILATOR
logic en_latched;

// Functional model of a positive-edge clock gate:
// capture EN only while CLK is low, then gate the high phase.
always_latch begin
    if (!CLK)
        en_latched = EN;
end

assign ENCLK = CLK & en_latched;
`else
logic EN_dly;
always @(EN) EN_dly = #1.5 EN; //DG: required to suppress timing violations
//this is clearly acceptable only if the EN is generated by the same clock we are gating

CKLNQD8
    mapped_ICGP(
    .Q(ENCLK),
    .TE(1'b0),
    .E(EN_dly),
    .CP(CLK));
`endif

endmodule
